### ISSUE TITLE
개발 테스트를 위한 DataCreator 구성

### ISSUE THREAD

**Issue by JungSeBin** [YAPP13-4/seba-api-v1#14]
디비는 계속해서 수정될거고, 그에 맞는 데이터를 매번 서로 맞추기는 어려워서
DataCreator를 두고 매번 테이블을 비우고 임시 데이터를 넣는 기능이 필요할 것 같아요

**Comment by livelikeabel** [comment]
DataCreator가 무엇인가요?(혹시 관련 링크 있으시면 부탁드려요! ㅎㅎ)

현재 저희는 각자 로컬 디비를 사용해서 개발하기로 했고 그에 따라 서로 디비 데이터가 다르게 될 수 있는 문제를 겪을거라 하시는데 동의 합니다!

저는 지금 로컬에서, music 데이터를 넣어보려고 하고 있는데, 세빈님이 이야기 하시는걸 사용하면 좋을거 같긴해요!
일단은 #13 , #16  그냥 진행하고 있을까요?

**Comment by seb5144** [comment]
DataCreator는 그냥 제가 임시로 붙힌 가명이에요 ㅋㅋ

서로 로컬에서 개발할 때는 데이터가 다를때마다 맞추는 작업이 어려워서 매번 데이터를 날리고 필요한 임시 데이터를 insert 하는 모듈이 있으면 편하거든요.

각자 작업을 하다가 db에 변경사항이 생기면 따로 공유할 필요없이 데이터를 생성해주는 모듈만 수정해주면, 다른사람들도 pull 받아서 바로 에러없이 진행할 수 있게 하는게 목표입니다 :)

**Comment by livelikeabel** [comment]
오오오 그런거 있으면 좋겠네요 ㅠㅠㅠㅠ
프론트에서도 작업을 하려면, 현재는 디비를 셋팅해야하는 상황이 되는데 이부분이 개발하는데 있어서 잘 해결 되었으면 좋겠어요!
(플레이팅에서는 testDB를 두어서, dev환경에서는 testDB에 api요청을 했었어요. 그래서 개발하는데 편했었어요 :) )

**Comment by JungSeBin** [comment]
넴 이건 어느정도 테이블이 정리된 이후에 진행하면 될듯

**Comment by livelikeabel** [comment]
으흠 개발편의를 위해 저는 빨리 셋팅 되면 좋겠다고 생각되는게, 
![image](https://user-images.githubusercontent.com/29794325/50558180-5019c180-0d2f-11e9-8535-1ebcc68ab3d6.png)
저는 이렇게 20개의 곡을 임시데이터로 넣었는데, 다른 분들도 하려면 이렇게 일일이 데이터를 넣어야 하는 불편함이 있을거 같아서요 ㅠㅠㅠ

**Comment by JungSeBin** [comment]
음... 그러게요, 테이블정리 될때마다 데이터 추가해도 되겠네요 ㅋㅋ
한번 진행해볼게요 👍

**Comment by livelikeabel** [comment]
넵넵 감사합니다! :)
